<?php

namespace Socialgeo\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
}
