services:
    socialgeo_user.registration.form.type:
        class: Socialgeo\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: socialgeo_user_registration }